### ISSUE TITLE
Example should be target: severless

### ISSUE THREAD

**Issue by justinwhall** [danielcondemarin/serverless-next.js#15] opened 2019-03-20 01:39 UTC
[Next Config](https://github.com/danielcondemarin/serverless-nextjs-plugin/blob/master/examples/basic-next-serverless-app/next.config.js) should be `target:serverless` no?

Also, `npm run dev` doesn't work really right now. May want to remove that script for now to climate confusion. However... What are you doing for a dev server? Right now, I'm maintaining two different servers essentially. 

1) Express for local dev
2) lamba/severless for anything but loca.

**Comment by danielcondemarin** [comment] 2019-03-20 13:36
Thanks for reporting @justinwhall 
I've updated the example to use `target: serverless`. 
Also, `npm run dev` should work fine now. Wasn't working before because it was trying to use the assets from S3.

**Comment by justinwhall** [comment] 2019-03-20 15:18
YA! I did notice the `assetPrefix`, even with removing that a route like `http://localhost:3000/post/9/` does not work while in dev which is expected as Next doesn't know about that route.

**Comment by danielcondemarin** [comment] 2019-03-20 20:45
Ah you're right. Right now the best I can think of is using `serverless-offline`, which will make the routing work, but then for local development is not great because HMR won't work. Will leave this open and look over the weekend what can be done 👍

**Comment by justinwhall** [comment] 2019-03-20 21:51
^^ Yar! `serverless-offline` works great. But no HMR. 

Regardless, plugin works great. Brings parody top client/SSR `query.foo`. Nice work here.

**Comment by romainquellec** [comment] 2019-03-21 11:06
One solution I can think of is using assetPrefix only in production using phase : https://github.com/zeit/next.js#custom-configuration

**Comment by justinwhall** [comment] 2019-03-21 15:07
> One solution I can think of is using assetPrefix only in production using phase : 
> https://github.com/zeit/next.js#custom-configuration

This won't help with HMR during development though?

**Comment by romainquellec** [comment] 2019-03-22 09:28
I shoud ! In dev (next dev), assetPrefix is unset, so it loads the assets as usual and in prod, it load the asset generated by the plugin.

**Comment by danielcondemarin** [comment] 2019-09-11 14:26
Duplicate of: https://github.com/danielcondemarin/serverless-next.js/issues/59

**Closed by danielcondemarin** 2019-09-11 14:26 UTC
Labels: needs-investigation
