### ISSUE TITLE
Change IAM permissions on Lamda functions

### ISSUE THREAD

**Issue by jaredready** [danielcondemarin/serverless-next.js#191] opened 2019-10-09 02:14 UTC
Right now this component deploys functions with all permissions, which is not really usable in a lot of AWS accounts. Least-privilege is how most people operate.

I would like to be able supply my own policy for the Lambdas to lock it down to exactly what it needs to access and no more.

**Comment by danielcondemarin** [comment] 2019-10-09 11:50
Closing as duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/183

**Closed by danielcondemarin** 2019-10-09 11:50 UTC
