### ISSUE TITLE
Latest commit breaks deploy

### ISSUE THREAD

**Issue by kevinswarner** [danielcondemarin/serverless-next.js#360] opened 2020-04-13 19:41 UTC
**Describe the bug**
I have not changed anything related to the use of the component since yesterday and went to perform "sls" and am now receiving the following error on deploy. I tried removing serverless-next.js and adding it back using yarn remove / yarn add. Same result.

I tried to revert specifically to serverless-next.js@1.9.8 and that did not fix the issue.

```
error:
  { [Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path:
   '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js' }

  6s › myApp › Error: ENOENT: no such file or directory, stat '/Users/kevinwarner/.serverless/components/registry/npm/serverless-next.js@1.9.9/node_modules/serverless-next.js/node_modules/next-aws-cloudfront/next-aws-cloudfront.js'
```

The latest commit looks to have made some changes related to the cloudfront component.

**Comment by danielcondemarin** [comment] 2020-04-13 19:45
I'm currently looking into this. Duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/359

**Closed by danielcondemarin** 2020-04-13 19:45 UTC

**Comment by kevinswarner** [comment] 2020-04-13 19:48
Thanks. I did not see that one. I will follow it, so feel free to close this one. Sorry for the dup.
