### ISSUE TITLE
RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation

### ISSUE THREAD

**Issue by ytwguru** [danielcondemarin/serverless-next.js#336] opened 2020-03-29 01:49 UTC
**Describe the bug**
After running serverless build is interrupted by the error

```
...
DEBUG ─ Creating lambda qqk7ltu-ni97e9 in the us-east-1 region.
error:
  { RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the CreateFunction operation
```

**To Reproduce**
1. Run serverless --debug

**Expected behavior**
Should build and deploy the code

**Comment by danielcondemarin** [comment] 2020-04-05 12:54
Duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/336

**Closed by danielcondemarin** 2020-04-05 12:54 UTC

**Comment by eenagy** [comment] 2020-06-07 13:40
This issue cannot be duplicate of itself, it was mostly likely closed by mistake. Please reopen it. @danielcondemarin

**Comment by danielcondemarin** [comment] 2020-06-07 13:42
Sorry! I actually meant a duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/236
