### ISSUE TITLE
photos in the public folder

### ISSUE THREAD

**Issue by PrimeObjects** [danielcondemarin/serverless-next.js#233] opened 2019-11-10 20:31 UTC
I have photos in the /public/images folder, it works fine when it runs locally. After deploying to AWS, I can see a public folder in my S3, However /images/file.mp4 does not show the photo.

Thanks lot
Gary

**Comment by danielcondemarin** [comment] 2019-11-11 21:09
Duplicate of https://github.com/danielcondemarin/serverless-next.js/issues/207

**Closed by danielcondemarin** 2019-11-11 21:09 UTC
