### ISSUE TITLE
'Unzipped size must be smaller than 262144000 bytes' because code for all pages is deployed to each Lambda

### ISSUE THREAD

**Issue by JonNode28** [danielcondemarin/serverless-next.js#335] opened 2020-03-27 16:27 UTC
**Describe the bug**
When the combined, unzipped, built code size for all pages is greater than the 250MB Lambda code size limit you get the error: ' Unzipped size must be smaller than 262144000 bytes'

I've created a repro here: https://github.com/JonNode28/nextjs-size-error-repro

**To Reproduce**
1. Clone the repro above
2. npm i
3. Add .env file to root in the format:
```
AWS_ACCESS_KEY_ID=<<Your key ID>>
AWS_SECRET_ACCESS_KEY=<<Your secret>>
```
4. sls deploy

**Expected behavior**
Pages should be packaged and deployed to lambdas independently to prevent this ceiling being hit.

**Additional context**
I bloated the build sizes by referencing aws-amplify (~9MB) and created 27 pages to push it over the threshold. This is basically how we encountered the problem ourselves. Adding the ```individually: true``` flag seems to create a seprarate code package for each page but that also contains the code for all pages, duplicated.

**Comment by JonNode28** [comment] 2020-03-27 16:30
We had this problem with the plugin but I believe the issue is actually worse for the component model as you're only deploying a single lambda@edge and don't even have the option of deplying the code for each page separately (if I understood correctly how it works...)

**Comment by vfarah-if** [comment] 2020-04-06 14:46
I can confirm experiencing the same issue. Is there any suggestions on how this can be resolved?

**Comment by danielcondemarin** [comment] 2020-04-06 19:43
The best suggestion so far is here https://github.com/danielcondemarin/serverless-next.js/issues/236#issuecomment-558522440. 
I'm also closing this as a duplicate of the original issue: https://github.com/danielcondemarin/serverless-next.js/issues/236

**Closed by danielcondemarin** 2020-04-06 19:43 UTC
