### ISSUE TITLE
Ability to configure all cloudfront inputs

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-next.js#270] opened 2019-12-29 21:02 UTC
One of the features that I always need to update is the ability to configure cloudfront. Rather than making one off input configurations for each feature (e.g. forwarding certain headers), can I suggest rather allowing one to configure any cloudfront options that are available from [@serverless/aws-cloudfront](https://github.com/serverless-components/aws-cloudfront), like so:

```
myNextApplication:
  component: serverless-next.js
  inputs:
     cloudfront:
        default:
            inputs here
        api:
            inputs here
```

The idea is that anything you have not set could be set by these inputs. For example, I need user-agent forwarding and I want to whitelist what cloudfront allows me to do regarding headers.

This would solve #240 #198 It would also make other future requests asking for cloudfront changes obsolete.

What do you think? I can get a PR for this out quite quickly.

**Comment by AaronMoat** [comment] 2019-12-31 11:37
This would potentially solve #274 too

**Comment by danielcondemarin** [comment] 2020-01-01 20:48
@barrysteyn This sounds great 🔥Feel free to PR and I'll review.

**Comment by stan-sack** [comment] 2020-01-18 04:32
+1 this would be a great feature. I'm having the same issue with user-agent headers and would also like to disable caching for some code paths which such as /user-profile because if the page is rendered on the server then currently it will be cached and shown to other users.

**Comment by stan-sack** [comment] 2020-01-18 05:48
I just did it myself: https://github.com/danielcondemarin/serverless-next.js/pull/282. Confirmed it works on my own deployment.

@danielcondemarin let me know what you think and i'll add some tests and update the docs.

**Comment by stan-sack** [comment] 2020-01-20 12:43
I've added tests and documentation. It looks like your remark markdown linter is broken. I dont think the issue its failing me for is valid

**Comment by barrysteyn** [comment] 2020-02-01 03:53
Hi, I am going to give this one a crack over the weekend. I do note that #282 is doing something similar, but it's not 100% what I had in mind.

**Comment by skycremaschinin** [comment] 2020-02-11 16:09
hi, 
i need this feature for enable http request and ipv6 disabling. When this pr would be merged?

**Comment by danielcondemarin** [comment] 2020-02-11 17:02
Sorry I forgot to close the issue. This has been merged already https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-nextjs-component/README.md#custom-cloudfront-configuration

**Closed by danielcondemarin** 2020-02-11 17:02 UTC
Labels: next component
